nome = input(" DIGITE SEU NOME: ")
print ("Letras no nome: {}".format(len(nome)))
print ("Seu nome maiusculo: {}".format(nome.upper()))
print ("Seu nome minusculo: {}".format(nome.lower()))
print ("Seu nome dividido: {}".format(nome.split()))
print ("Seu primeiro nome: {}".format(nome.split()[0]))
print ("Seu nome junto: {}".format('-'.join(nome)))
print ("Letras no primeiro nome: {}".format(len(nome.split()[0])))
print ("seu nome junto: {}".format(nome.strip()))
separado = nome.split()
print ("seu nome junto: {}".format(''.join(separado)))
print ("seu nome todo junto tem {}".format(len(''.join(separado))))
